### ISSUE TITLE
Disable Smart Save and Click on Manual Save- Changes not Persisted

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#28]
**Describe the bug**
I have clicked on disable smart and manually clicking on save and have noticed the file with timestamp name example is getting updated -  _20220110122045.tm  but the the timestamp of the opened .tm is not getting changed

**To Reproduce**
1.Disable smart save
'![Step1](https://user-images.githubusercontent.com/31912418/148782878-8d258cd7-7bab-4bf2-8fed-f66f1e030bf9.PNG)

3.Make some changes on the threat model and click on save
4. Time stamp of the .tm files are not changed.  Data is not persisted,.

**Expected behavior**
Without smart save save should occur

**Screenshots**
![Step2-SavedNew](https://user-images.githubusercontent.com/31912418/148784410-5b56d205-fc3d-43a7-9d6f-3c1b5d86c7f0.png)

Directory screen shot
![image](https://user-images.githubusercontent.com/31912418/148784628-f1106d45-3a2c-4e23-9386-01aa7e2af3a7.png)

**Additional context**
Version 1.5.1.0

**Comment by simonec73** [comment]
This is by design. It is a consequence of the fact that you have disabled SmartSave and that you have opened the file with the suffix. To get the behavior you desire, you have to open the file without the suffix.
But the recommended way to go is to enable SmartSave and open the file without the suffix. This will allow getting a few copies back in time, which will safeguard your work in case of a crash or if you do some mistakes. I know, this is a poor workaround for the fact that I haven't implemented Undo, yet. This is on top of my list of wanted features.

**Comment by rsrinivasanhome** [comment]
I checked again it is saving but the timestamp of the .tm file is not changing.   But when I open the file I am seeing the changes.
Do I need I need to copy all the allied files  for taking a backup  in my case based on the screen shot it would be 

- Template1fromAzureModify_timestamp.tm
- Template1fromAzureModify_differenttimestamp.tm
- Template1fromAzureModify.tmlock
- Template1fromAzureModify.tm

**Comment by rsrinivasanhome** [comment]
Sorry question answered  -  "The original file will be replaced every time with the latest version"
