### ISSUE TITLE
when Opening Diagram is cluttered

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#74]
**Describe the bug**
I space my diagram and save the threat model version using tms 2.2.1.0.  When reopening it is cluttered . 

**To Reproduce**
1. I Open a threat model
2. I evenly space out the diagram 
3. Click on save remains spaced.
4. Close the diagram and repoen
5. Observed the diagram is cluttered .

**Expected behavior**
The diagram is displayed the same way it was saved .

What is the recommended way to handled this issue ? I think some new features are available to handle the issue now.  
Please advise .

Is there a recommend limit on number of diagarams we should have in a threat model ?

**Comment by simonec73** [comment]
I cannot reproduce. The issue was solved with version 2.2.1 by removing Hi-DPI awareness. New diagrams should not have this issue.
The Fix current diagram functionality in the Diagram ribbon might be able to help.

Please let me know if the problem persists. It would be great if you could share a repo.

**Comment by rsrinivasanhome** [comment]
I tried manually moving the objects in the diagram and when I reopen they were cluttered .
As you suggested I clicked on  Fix current diagram and it did the trick.
