### ISSUE TITLE
Export For Azure Dev Ops Features

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#88]
**Is your feature request related to a problem? Please describe.**
We are not using Azure Dev Ops but using the csv file it generates to push into jira.  Now we face  2 issues.

1)Special characters visible in the csv
"<br>" - >  \n
"&#39;" -> '
"&nbsp;" - > (space)
"&quot;" -> '
Can we have some config which will prevent these special characters from being exported ?

2) Need Affected Objects along with Description

The csv contains 4 columns 

1)WorkItem
2)Title
3)Description
4)State

Now if this were pushed into the ticket tracking application we would just know the mitigation but not know how many times it needs to be applied and where .

In the Summary Report we have a field name - "Affected Objects"

Can we have the data in "Affected Objects" concatenated with Description (column 3)

With this change any ticketing tool should be able to consume the csv file generated .

**Comment by simonec73** [comment]
For the first point, I might do something, but you must provide a better explanation of what are the problems you are seeing, and the type of changes you need. For example, it seems reasonable to change the quote char with the single quote, but is that what you are asking? On the other hand, I do not understand what most of the changes you are requiring, including **" " - > (space)** means. And please, consider that if there is something that is too specific to your use scenario, I might not support it.

For the second point, I fear I cannot help you because it is too specific of your use-case. You might want to create an Extension to generate a CSV file with exactly the characteristics you need.

**Comment by simonec73** [comment]
**Issue 1 works as intended**. I've created an example like the one you can see below:
![image](https://github.com/user-attachments/assets/77b40174-abd2-4ac8-a987-ea334d1592a0)
When I import it into ADO, I see this:
![image](https://github.com/user-attachments/assets/1d2d9dfa-da8f-4c76-a787-0fb6505d3454)
This is pretty good as a result. I'm not fixing it.

**Issue 2 works as designed**. I know about this, but I'm not sure how it should be addressed. The fact is that the instances are logical entities which make sense for the threat model, and if decontextualized they might be misleading for the developers. For this reason, I decided to leave the description untouched. I might decide to add that information at a later stage. An idea might be  to add an intermediate step, asking the user if she or he wants to add the list of affected entities. In your example, you would have something like:
This is the description of the mitigation.

- [Process] Instance 1
- [Process] Instance 2

Would that work?

**Comment by rsrinivasanhome** [comment]
Yeah I think so
